Fix lint warnings and specify compiler version
hicommonwealth/edgeth-bridge pull request #2
Opened 2018-12-22 18:58 UTC by DemiMarie

Truffle needs a specific compiler version to be specified.  Also, some
lint warnings could be fixed.

2018-12-22 19:51 UTC, drewstone requested changes
Have you run all tests and ensured they pass?

2018-12-22 19:51 UTC, drewstone commented on contracts/EdgewareERC20.sol
> +     * @param account The address to burn tokens from.
Spacing is off by 1.

2018-12-22 19:51 UTC, drewstone commented on contracts/ValidatorSet.sol
> +            require(recAddr == addresses[signers[i]], "Invalid recipient address");
Spacing is off.

2018-12-23 00:15 UTC, DemiMarie commented
@drewstone I tried to run the tests, but failed.  What is the best way to run them?

2018-12-23 00:17 UTC, DemiMarie commented on contracts/ValidatorSet.sol
> +            require(recAddr == addresses[signers[i]], "Invalid recipient address");
Fixed.

2018-12-26 17:12 UTC, DemiMarie commented
@drewstone Running `truffle test` fails on master and on this branch, with obscure errors in both cases.

2018-12-26 17:12 UTC, DemiMarie commented
That said, I am not sure what version of Truffle to use.

2018-12-26 22:02 UTC, DemiMarie commented
@drewstone The tests now pass on my system (Truffle 5.0.0).

2018-12-27 15:46 UTC, drewstone approved these changes

2018-12-27 15:47 UTC, drewstone commented
Look good! Thanks @DemiMarie !

2018-12-27 15:47 UTC, merged